# Generated by Django 5.1.3 on 2024-11-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=100, null=True, verbose_name="Full name"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Phone number"
            ),
        ),
    ]
